### ISSUE TITLE
Optional Stronger Error Reporting

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/easycurses-rs#12]
It has been asked for IO operations to have a `Result` type.

However there's no result data to be had most of the time, so most results would be `Result<()`, and there's also no error information to be had most of the time, so we'd be using `Result<(),()>` everywhere.

Except that to be used with the `?` operator for early return at the moment, the error case needs to implement `Error`, so we need to use some custom type that we add an `Error` instance for, `Result<(),EasyCursesError>`. There's an RFC that'll help clear up that particular issue.

```
https://github.com/rust-lang/rust/issues/31436
```

I think the best way to do it would be to have a wrapper struct that called the inner methods, checked for false, and then returned an appropriate result. That way people start with the current `bool` and `Option` results, and then they can upgrade their usage to `Result` based types if they want to.

**Comment by sollyucko** [comment]
Not sure if `Result<(), ()>` or `Option<()>` would be better, but IMO either would be better than `bool`, since they can be used with `?`, for example. For any code that does check the return value, it can just use `.is_ok()` or `.is_some()`. If you want, I could make this change and submit a PR.

**Comment by sollyucko** [comment]
Also, `Option` might be best since that's what's used elsewhere, e.g. `EasyCurses::initialize_system`, `EasyCurses::get_input`, etc.

**Comment by Lokathor** [comment]
I think this issue might predate the `?` operator XD

I don't really work on this crate any more but if you'd like to do a PR I'd be happy to merge it and get a release out.

**Comment by sollyucko** [comment]
OK, sure!
