### ISSUE TITLE
get_cursor_xy documentation possibly incorrect

### ISSUE THREAD

**Issue by coder543** [Lokathor/easycurses-rs#13]
[Here](https://docs.rs/easycurses/0.7.1/easycurses/struct.EasyCurses.html#method.get_cursor_xy), it says that it is relative to the bottom right, and again, [over here](https://github.com/Lokathor/easycurses-rs/blob/master/examples/bounds.rs#L34), it is claimed to be x-inverted by saying that the '-' will print in the lower-left.

To make sure I wasn't crazy, I tested this with both ncurses and pdcurses backends, and those comments appear to be incorrect. Maybe at one point in time the x-axis was planned to be inverted.

**Comment by Lokathor** [comment]
Ah, no, i just wrote the docs wrong. I will fix it and push a patch to crates.io soon as i get home

**Comment by Lokathor** [comment]
Forgot to comment here in the issue until just now, but a new version was pushed with some docs fixes.
